//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHotelIS.DTO
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using SimpleHotelIS.Models;
    
    public partial class ZakaznikDTO : IEntityConvertible<Zakaznik, ZakaznikDTO>
    {
        public ZakaznikDTO()
        {
    	}
    
        public ZakaznikDTO(Zakaznik entity)
        {
    	}
    
    	public  Zakaznik ToEntity()
    	{
    		Zakaznik entity = new  Zakaznik();
    		entity.Id = this.Id;
    		entity.meno = this.meno;
    		entity.priezvisko = this.priezvisko;
    		entity.kontakt = this.kontakt;
    		return entity;
    	}
    
    
        public int Id { get; set; }
        public string meno { get; set; }
        public string priezvisko { get; set; }
        public string kontakt { get; set; }
    	//dong
    		//susu
        public virtual ICollection<int> Rezervacias { get; set; }
        public virtual ICollection<int> Platbas { get; set; }
        public virtual ICollection<int> Pobyts { get; set; }
    }
}
