//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHotelIS.Controllers.CRUDControllers
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using SimpleHotelIS.Models;
    using SimpleHotelIS.DTO;
    using SimpleHotelIS.BusinessPipelines;
    
    public partial class IzbaController  : Controller
    {
    
        	private ICrudServiceProvider<Izba, IzbaDTO> icsp;
        
        	public IzbaController
        		(
        			ICrudServiceProvider<Izba, IzbaDTO> icsp
        		)
        	{
        		this.icsp = icsp;
        	}
    
            [HttpGet]
            public ActionResult Index()
            {
                return RedirectToActionPermanent("List");
            }
        
            [HttpGet]
            public ActionResult GetById(int id)
            {
                var result = icsp.CreateIGetByIdService().Invoke(this, id);
                return View("Detail", result);
            }
                
            [HttpGet]
            public ActionResult GetQueryable()
            {
                var querystring = this.Request.QueryString;
                var result = icsp.CreateIAsQueryableService().Invoke(this);
                return View("List", result);
            }
    
            [HttpGet]
            public ActionResult Create()
            {
                return View("Create");
            }
    
            [HttpPost]
            public ActionResult Create(IzbaDTO dto)
            {
    			try
    			{
    				icsp.CreateICreateService().Invoke(this, dto);
    				return View("Detail");
    			} catch ( Exception e )
    			{
    				ViewBag.Original = dto;
    				ViewBag.Reasons = e;
    				return View("Create");
    			}
            }
    
            [HttpGet]
            public ActionResult Update(int id)
            {
    			var result = icsp.CreateIGetByIdService().Invoke(this, id);
                return View("Update", result);
            }
    
            [HttpPost]
            public ActionResult Update(IzbaDTO dto)
            {
    			try
    			{
    				icsp.CreateIUpdateService().Invoke(this, dto);
    				return View("Detail");
    			} catch ( Exception e )
    			{
    				ViewBag.Original = dto;
    				ViewBag.Reasons = e;
    				return View("Update");
    			}
            }
    
            [HttpGet]
            public ActionResult Delete(int id)
            {
    			var result = icsp.CreateIGetByIdService().Invoke(this, id);
    			ViewBag.ShowDeleteConfirmation = true;
                return View("Detail", id);
            }
    
            [HttpPost]
            public ActionResult Delete(int id)
            {
    			try
    			{
    				icsp.CreateIDeleteService().Invoke(this, id);
    				return View("List");
    			} catch ( Exception e )
    			{
    				var result = icsp.CreateIGetByIdService().Invoke(this, id);
    				ViewBag.Reasons = e;
    				return View("Detail", result);
    			}
            }
        
    }
}
