//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHotelIS.ApiControllers
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web.Http;
    using System.Web;
    using SimpleHotelIS.Models;
    using SimpleHotelIS.DTO;
    using SimpleHotelIS.BussinesPipelines;
    
    public partial class IzbaController  : ApiController
    {
    
        	private ICrudServiceProvider icsp;
        
        	public IzbaController
        		(
        			ICrudServiceProvider icsp
        		)
        	{
        		this.icsp = icsp;
        	}
    
            public IEnumerable<IzbaDTO> Get()
        	{
                return icsp.GetAsQueryableService<Izba, IzbaDTO>().invoke(this).Take(10);
        	}
        
        	public IzbaDTO GetById(int id)
        	{
                return icsp.GetByIdService<Izba, IzbaDTO>().invoke(this, id);
        	}
        
        	[Queryable]
        	public IQueryable<IzbaDTO> GetQueryable()
        	{
                return icsp.GetAsQueryableService<Izba, IzbaDTO>().invoke(this);
        	}
        
        	public System.Net.Http.HttpResponseMessage Post(IzbaDTO dto)
        	{
                icsp.GetCreateService<Izba, IzbaDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Put(IzbaDTO dto)
        	{
                icsp.GetUpdateService<Izba, IzbaDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(IzbaDTO dto)
        	{
                icsp.GetDeleteService<Izba, IzbaDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(int id)
        	{
                icsp.GetDeleteService<Izba, IzbaDTO>().Invoke(this, new IzbaDTO { Id = id });
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
    }
}
