//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHotelIS.ApiControllers
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web.Http;
    using System.Web;
    using SimpleHotelIS.Models;
    using SimpleHotelIS.DTO;
    using SimpleHotelIS.BussinesPipelines;
    
    public partial class PobytController  : ApiController
    {
    
        	private ICrudServiceProvider icsp;
        
        	public PobytController
        		(
        			ICrudServiceProvider icsp
        		)
        	{
        		this.icsp = icsp;
        	}
    
            public IEnumerable<PobytDTO> Get()
        	{
                return icsp.GetAsQueryableService<Pobyt, PobytDTO>().invoke(this).Take(10);
        	}
        
        	public PobytDTO GetById(int id)
        	{
                return icsp.GetByIdService<Pobyt, PobytDTO>().invoke(this, id);
        	}
        
        	[Queryable]
        	public IQueryable<PobytDTO> GetQueryable()
        	{
                return icsp.GetAsQueryableService<Pobyt, PobytDTO>().invoke(this);
        	}
        
        	public System.Net.Http.HttpResponseMessage Post(PobytDTO dto)
        	{
                icsp.GetCreateService<Pobyt, PobytDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Put(PobytDTO dto)
        	{
                icsp.GetUpdateService<Pobyt, PobytDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(PobytDTO dto)
        	{
                icsp.GetDeleteService<Pobyt, PobytDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(int id)
        	{
                icsp.GetDeleteService<Pobyt, PobytDTO>().Invoke(this, new PobytDTO { Id = id });
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
    }
}
