//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHotelIS.ApiControllers
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web.Http;
    using System.Web;
    using SimpleHotelIS.Models;
    using SimpleHotelIS.DTO;
    using SimpleHotelIS.BussinesPipelines;
    
    public partial class RezervaciaController  : ApiController
    {
    
        	private ICrudServiceProvider icsp;
        
        	public RezervaciaController
        		(
        			ICrudServiceProvider icsp
        		)
        	{
        		this.icsp = icsp;
        	}
    
            public IEnumerable<RezervaciaDTO> Get()
        	{
                return icsp.GetAsQueryableService<Rezervacia, RezervaciaDTO>().invoke(this).Take(10);
        	}
        
        	public RezervaciaDTO GetById(int id)
        	{
                return icsp.GetByIdService<Rezervacia, RezervaciaDTO>().invoke(this, id);
        	}
        
        	[Queryable]
        	public IQueryable<RezervaciaDTO> GetQueryable()
        	{
                return icsp.GetAsQueryableService<Rezervacia, RezervaciaDTO>().invoke(this);
        	}
        
        	public System.Net.Http.HttpResponseMessage Post(RezervaciaDTO dto)
        	{
                icsp.GetCreateService<Rezervacia, RezervaciaDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Put(RezervaciaDTO dto)
        	{
                icsp.GetUpdateService<Rezervacia, RezervaciaDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(RezervaciaDTO dto)
        	{
                icsp.GetDeleteService<Rezervacia, RezervaciaDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(int id)
        	{
                icsp.GetDeleteService<Rezervacia, RezervaciaDTO>().Invoke(this, new RezervaciaDTO { Id = id });
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
    }
}
