//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHotelIS.ApiControllers
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web.Http;
    using System.Web;
    using SimpleHotelIS.Models;
    using SimpleHotelIS.DTO;
    using SimpleHotelIS.BussinesPipelines;
    
    public partial class SluzbyController  : ApiController
    {
    
        	private ICrudServiceProvider icsp;
        
        	public SluzbyController
        		(
        			ICrudServiceProvider icsp
        		)
        	{
        		this.icsp = icsp;
        	}
    
            public IEnumerable<SluzbyDTO> Get()
        	{
                return icsp.GetAsQueryableService<Sluzby, SluzbyDTO>().invoke(this).Take(10);
        	}
        
        	public SluzbyDTO GetById(int id)
        	{
                return icsp.GetByIdService<Sluzby, SluzbyDTO>().invoke(this, id);
        	}
        
        	[Queryable]
        	public IQueryable<SluzbyDTO> GetQueryable()
        	{
                return icsp.GetAsQueryableService<Sluzby, SluzbyDTO>().invoke(this);
        	}
        
        	public System.Net.Http.HttpResponseMessage Post(SluzbyDTO dto)
        	{
                icsp.GetCreateService<Sluzby, SluzbyDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Put(SluzbyDTO dto)
        	{
                icsp.GetUpdateService<Sluzby, SluzbyDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(SluzbyDTO dto)
        	{
                icsp.GetDeleteService<Sluzby, SluzbyDTO>().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(int id)
        	{
                icsp.GetDeleteService<Sluzby, SluzbyDTO>().Invoke(this, new SluzbyDTO { Id = id });
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
    }
}
