//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace SimpleHotelIS.Models
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class hotelEntities : DbContext
    {
        static hotelEntities()
    	{ 
    		Database.SetInitializer<hotelEntities>(null);
    	}
    	
    	public hotelEntities() : base("name=hotelEntities")
        {
        }
    	
    	public hotelEntities(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public hotelEntities(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public hotelEntities(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public hotelEntities(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    		modelBuilder.Conventions.Remove<IncludeMetadataConvention>();
    		modelBuilder.Configurations.Add(new Izba_Mapping());
    		modelBuilder.Configurations.Add(new Platba_Mapping());
    		modelBuilder.Configurations.Add(new Pobyt_Mapping());
    		modelBuilder.Configurations.Add(new Rezervacia_Mapping());
    		modelBuilder.Configurations.Add(new Sluzby_Mapping());
    		modelBuilder.Configurations.Add(new Zakaznik_Mapping());
        }
    	
        public DbSet<Zakaznik> Zakazniks { get; set; }
        public DbSet<Rezervacia> Rezervacias { get; set; }
        public DbSet<Pobyt> Pobyts { get; set; }
        public DbSet<Izba> Izbas { get; set; }
        public DbSet<Platba> Platbas { get; set; }
        public DbSet<Sluzby> Sluzbies { get; set; }
    }
}
