//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHotelIS.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Pobyt
    {
        public Pobyt()
        {
            this.Izbas = new HashSet<Izba>();
            this.Sluzbies = new HashSet<Sluzby>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Izba> Izbas { get; set; }
        public virtual ICollection<Sluzby> Sluzbies { get; set; }
        public virtual Zakaznik Zakaznik { get; set; }
        public virtual int ZakaznikId { get; set; }
    }
}
