//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHotelIS.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaznik
    {
        public Zakaznik()
        {
            this.Rezervacias = new HashSet<Rezervacia>();
            this.Platbas = new HashSet<Platba>();
            this.Pobyts = new HashSet<Pobyt>();
        }
    
        public int Id { get; set; }
        public string meno { get; set; }
        public string priezvisko { get; set; }
        public string kontakt { get; set; }
    
        public virtual ICollection<Rezervacia> Rezervacias { get; set; }
        public virtual ICollection<Platba> Platbas { get; set; }
        public virtual ICollection<Pobyt> Pobyts { get; set; }
    }
}
