//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHotelIS.ApiControllers.CRUDApiControllers
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web.Http;
    using System.Web;
    using SimpleHotelIS.Models;
    using SimpleHotelIS.DTO;
    using SimpleHotelIS.BusinessPipelines;
    
    public partial class PlatbaController  : ApiController
    {
    
        	private ICrudServiceProvider<Platba, PlatbaDTO> icsp;
        
        	public PlatbaController
        		(
        			ICrudServiceProvider<Platba, PlatbaDTO> icsp
        		)
        	{
        		this.icsp = icsp;
        	}
    
            public IEnumerable<PlatbaDTO> Get()
        	{
                return icsp.CreateIAsQueryableService().Invoke(this).Take(10);
        	}
        
        	public PlatbaDTO GetById(int id)
        	{
                return icsp.CreateIGetByIdService().Invoke(this, id);
        	}
        
        	[Queryable]
        	public IQueryable<PlatbaDTO> GetQueryable()
        	{
                return icsp.CreateIAsQueryableService().Invoke(this);
        	}
        
        	public System.Net.Http.HttpResponseMessage Post(PlatbaDTO dto)
        	{
                icsp.CreateICreateService().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Put(PlatbaDTO dto)
        	{
                icsp.CreateIUpdateService().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(PlatbaDTO dto)
        	{
                icsp.CreateIDeleteService().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(int id)
        	{
                icsp.CreateIDeleteService().Invoke(this, new PlatbaDTO { Id = id });
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
    }
}
