//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleHotelIS.ApiControllers.CRUDApiControllers
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web.Http;
    using System.Web;
    using SimpleHotelIS.Models;
    using SimpleHotelIS.DTO;
    using SimpleHotelIS.BusinessPipelines;
    
    public partial class ZakaznikController  : ApiController
    {
    
        	private ICrudServiceProvider<Zakaznik, ZakaznikDTO> icsp;
        
        	public ZakaznikController
        		(
        			ICrudServiceProvider<Zakaznik, ZakaznikDTO> icsp
        		)
        	{
        		this.icsp = icsp;
        	}
    
            public IEnumerable<ZakaznikDTO> Get()
        	{
                return icsp.CreateIAsQueryableService().Invoke(this).Take(10);
        	}
        
        	public ZakaznikDTO GetById(int id)
        	{
                return icsp.CreateIGetByIdService().Invoke(this, id);
        	}
        
        	[Queryable]
        	public IQueryable<ZakaznikDTO> GetQueryable()
        	{
                return icsp.CreateIAsQueryableService().Invoke(this);
        	}
        
        	public System.Net.Http.HttpResponseMessage Post(ZakaznikDTO dto)
        	{
                icsp.CreateICreateService().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Put(ZakaznikDTO dto)
        	{
                icsp.CreateIUpdateService().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(ZakaznikDTO dto)
        	{
                icsp.CreateIDeleteService().Invoke(this, dto);
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
        
        	public System.Net.Http.HttpResponseMessage Delete(int id)
        	{
                icsp.CreateIDeleteService().Invoke(this, new ZakaznikDTO { Id = id });
                return new System.Net.Http.HttpResponseMessage(HttpStatusCode.NoContent);
        	}
    }
}
